name: Create release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          ./build.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.build.outputs.version }}
          name: ${{ steps.build.outputs.version }}
          files: ${{ steps.build.outputs.dist_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
